import { useState } from 'react';
import { ArrowRight, ArrowUpRight, BookOpen, CalendarDays, Check, CheckCircle2, ClipboardCheck, Clock3, GraduationCap, Leaf, Play, Plus, Search, ShieldCheck, Sparkles, Upload, Users, Video } from 'lucide-react';
import { useDemo } from './demo';
import { ActionForm, type FormKind } from './forms';
import { demoMedia } from './integrations';
import { available, canAdmin, canSeeCourse, featureLabels, isTeacher, visibleLessons, type AttendanceStatus, type Feature, type Session } from './model';
import { Avatar, Badge, Button, CheckLabel, CourseArt, CourseCard, Empty, Field, Modal, Notice, PageHeading, SectionHeading, Unavailable, dateLabel, timeLabel } from './ui';

function useScope() {
  const { state, viewer } = useDemo();
  const courses = state.courses.filter(c => canSeeCourse(c, viewer));
  const sessions = state.sessions.filter(s => s.orgId === viewer.orgId && courses.some(c => c.id === s.courseId)).sort((a,b) => `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`));
  return { courses, sessions, lessons: visibleLessons(state, viewer), teacher: isTeacher(viewer.role) };
}
export function Dashboard() {
  const { state, viewer } = useDemo(); const { courses, sessions, lessons, teacher } = useScope();
  const [form, setForm] = useState<FormKind | null>(null);
  const name = state.members.find(m => m.id === viewer.userId)?.name.split(' ')[0] || 'there';
  const next = available(state, viewer, 'live') ? sessions[0] : undefined;
  const course = courses.find(c => c.id === next?.courseId);
  const students = new Set(courses.flatMap(c => c.studentIds)).size;
  const completed = lessons.filter(l => l.completeBy.includes(viewer.userId)).length;
  const pending = state.submissions.filter(s => !s.published && s.orgId === viewer.orgId && state.assignments.some(a => a.id === s.assignmentId && courses.some(c => c.id === a.courseId))).length;
  const stats = teacher ? [ { icon: BookOpen, value: courses.length, label: 'Active courses', detail: 'Room for every idea' }, { icon: Users, value: students, label: 'Learners', detail: 'Growing together' }, { icon: Video, value: lessons.filter(l => l.status === 'published').length, label: 'Published lessons', detail: 'Ready to explore' }, { icon: ClipboardCheck, value: available(state, viewer, 'assessments') ? pending : '—', label: 'Reviews to give', detail: 'A little feedback goes far' } ] : [ { icon: BookOpen, value: courses.length, label: 'My courses', detail: 'New worlds to explore' }, { icon: CheckCircle2, value: completed, label: 'Lessons completed', detail: 'One step at a time' }, { icon: CalendarDays, value: available(state, viewer, 'live') ? sessions.length : '—', label: 'Scheduled classes', detail: 'Learn alongside your class' }, { icon: GraduationCap, value: state.submissions.filter(s => s.studentId === viewer.userId && s.published).length, label: 'Published results', detail: 'See how you’re growing' } ];
  return <><PageHeading eyebrow="YOUR LEARNING SPACE" title={`Good to see you, ${name}.`} description={teacher ? 'Small moments of teaching. A world of possibility.' : 'Stay curious. Your next discovery is just around the corner.'} action={teacher && available(state, viewer, 'live') ? <Button onClick={() => setForm('session')}><Plus size={17}/>Schedule a class</Button> : <a className="button primary" href="#/courses">Explore my courses <ArrowUpRight size={17}/></a>}/>
    <div className="dashboard-top"><section className="hero-card"><div className="hero-copy"><Badge tone="light"><span className="status-dot"/>{next ? 'YOUR NEXT LIVE CLASS' : 'A GOOD DAY TO BEGIN'}</Badge><h2>{next ? 'Big ideas start\nwith a little curiosity.' : 'Make space for\nsomething new.'}</h2><p>{next ? `${course?.subject} · ${course?.grade} · ${course?.batch}` : 'Explore your courses and keep learning, one thoughtful step at a time.'}</p>{next && <div className="hero-time"><CalendarDays size={16}/>{dateLabel(next.date)}<span>·</span><Clock3 size={16}/>{timeLabel(next.time)}</div>}<a className="button hero-button" href={next ? `#/sessions/${next.id}` : '#/courses'}>{teacher ? next ? 'View class details' : 'View courses' : next ? 'Get ready for class' : 'Explore courses'}<ArrowUpRight size={17}/></a></div><div className="hero-art" aria-hidden="true"><div className="sun"/><div className="arch arch-one"/><div className="arch arch-two"/><div className="orb"/><span className="spark spark-one">✳</span><span className="spark spark-two">✧</span><div className="art-caption">a little more<br/><i>possibility.</i></div></div></section>
    <section className="focus-card"><div className="focus-top"><span className="eyebrow">{teacher ? 'ON YOUR RADAR' : 'YOUR LEARNING PATH'}</span><Leaf size={19}/></div><h3>{teacher ? 'Every learner\ncan flourish.' : 'Progress looks\ngood on you.'}</h3><p>{teacher ? 'A thoughtful next step for your classroom.' : `${completed} of ${lessons.length} available lessons marked complete in this demo.`}</p><div className="focus-bottom">{teacher ? <><div className="avatar-stack">{['AM','IN','NS'].map(i => <Avatar key={i} initials={i} small/>)}</div><span>{students} curious minds</span></> : <div className="progress-track"><span style={{ width: `${lessons.length ? completed/lessons.length*100 : 0}%` }}/></div>}</div><a href={teacher ? '#/assessments' : '#/recordings'} className="text-link">{teacher ? 'Give a little feedback' : 'Continue learning'} <ArrowRight size={15}/></a></section></div>
    <div className="stats-grid">{stats.map(s => <div className="stat-card" key={s.label}><div className="stat-top"><span>{s.label}</span><s.icon size={18}/></div><strong>{s.value}</strong><small>{s.detail}</small></div>)}</div>
    <SectionHeading title={teacher ? 'Your classroom, at a glance' : 'Keep your curiosity going'} href="#/courses"/>
    <div className="course-grid">{courses.slice(0,3).map(c => <CourseCard key={c.id} course={c} detail={teacher ? `${c.studentIds.length} learners` : `${lessons.filter(l => l.courseId === c.id).length} available lessons`}/>)}</div>{!courses.length && <Empty title="Your first course belongs here" text="An admin-assigned teacher can create a course and add a fictional learner."/>}
    <div className="dashboard-bottom"><section className="panel"><SectionHeading title="Coming up" href="#/sessions"/>{available(state, viewer, 'live') && sessions.length ? sessions.slice(0,3).map(s => <SessionRow key={s.id} session={s}/>) : <p className="muted">No enabled sessions to show.</p>}</section><section className="note-card"><Sparkles size={23}/><span className="eyebrow">A THOUGHT TO TAKE WITH YOU</span><blockquote>“The beautiful thing about learning is that nobody can take it away from you.”</blockquote><span>— B. B. King</span><div className="note-line"/></section></div>
    {form && <ActionForm kind={form} close={() => setForm(null)}/>}</>;
}
export function SessionRow({ session }: { session: Session }) { const { state } = useDemo(); const c = state.courses.find(c => c.id === session.courseId); return <a className="session-row" href={`#/sessions/${session.id}`}><span className={`session-icon ${c?.color}`}><Video size={18}/></span><div><strong>{session.title}</strong><span>{c?.subject} · {dateLabel(session.date)} · {timeLabel(session.time)}</span></div><ArrowUpRight size={17}/></a>; }

export function Courses() {
  const { viewer } = useDemo(); const { courses, lessons, teacher } = useScope(); const [search, setSearch] = useState(''); const [form, setForm] = useState(false);
  const filtered = courses.filter(c => `${c.title} ${c.subject} ${c.batch}`.toLowerCase().includes(search.toLowerCase()));
  return <><PageHeading eyebrow="ROOM TO GROW" title={teacher ? 'Your courses' : 'My courses'} description="A few familiar subjects. Endless new possibilities." action={canAdmin(viewer.role) && <Button onClick={() => setForm(true)}><Plus size={17}/>Create course</Button>}/><div className="list-toolbar"><label className="search-field"><Search size={17}/><input aria-label="Search courses" placeholder="Find a course or subject…" value={search} onChange={e => setSearch(e.target.value)}/></label><span className="muted">{filtered.length} courses</span></div><div className="course-grid">{filtered.map(c => <CourseCard key={c.id} course={c} detail={teacher ? `${c.studentIds.length} learners` : `${lessons.filter(l => l.courseId === c.id).length} lessons`}/>)}</div>{!filtered.length && <Empty title="No courses found" text={search ? 'Try another subject or course name.' : 'Courses appear here once an admin-assigned teacher sets them up.'}/>} {form && <ActionForm kind="course" close={() => setForm(false)}/>}</>;
}
export function CourseDetail({ id }: { id: string }) {
  const { state, viewer } = useDemo(); const { courses, lessons, teacher } = useScope(); const course = courses.find(c => c.id === id); const [tab, setTab] = useState('lessons'); const [form, setForm] = useState<FormKind | null>(null);
  if (!course) return <Unavailable title="This course isn’t in your classroom" text="Switch back to your courses to see what is available in this demo role and organization."/>;
  const list = lessons.filter(l => l.courseId === id); const roster = state.members.filter(m => m.orgId === viewer.orgId && course.studentIds.includes(m.id));
  return <><a className="back-link" href="#/courses">← All courses</a><div className="course-detail-hero"><div><Badge tone={course.color}>{course.subject} · {course.grade}</Badge><h1>{course.title}</h1><p>{course.description}</p><div className="inline-meta"><Users size={16}/>{course.studentIds.length} learners<span>·</span>{course.batch}</div></div><CourseArt color={course.color} large/></div><div className="tabs" role="tablist" aria-label="Course views">{['lessons', 'schedule', ...(teacher ? ['roster'] : [])].map(t => <button key={t} role="tab" aria-selected={tab === t} onClick={() => setTab(t)}>{t === 'lessons' ? 'Lesson library' : t === 'schedule' ? 'Class schedule' : 'Class roster'}</button>)}</div>
    {tab === 'lessons' && <><SectionHeading title="A lesson at a time" action={teacher && available(state, viewer, 'recordings') && <Button variant="secondary" onClick={() => setForm('recording')}><Plus size={16}/>Add recording</Button>}/>{!available(state, viewer, 'recordings') ? <Unavailable/> : list.length ? <div className="panel lesson-list">{list.map((l,i) => <a className="lesson-row" key={l.id} href={`#/recordings/${l.id}`}><span className="lesson-number">{String(i+1).padStart(2,'0')}</span><div><strong>{l.title}</strong><span>{l.duration} min · {l.age} · {l.status === 'published' ? 'Teacher-approved' : 'Not visible to students'}</span></div>{l.completeBy.includes(viewer.userId) ? <CheckCircle2 size={20} className="green"/> : <Badge tone={l.status === 'published' ? 'sage' : 'peach'}>{l.status === 'review' ? 'In review' : l.status}</Badge>}<Play size={17}/></a>)}</div> : <Empty title="The first lesson is still ahead" text="Reviewed and published lessons will appear here."/>}</>}
    {tab === 'schedule' && <><SectionHeading title="Learn together" action={teacher && available(state, viewer, 'live') && <Button variant="secondary" onClick={() => setForm('session')}><Plus size={16}/>Schedule class</Button>}/>{available(state, viewer, 'live') ? <div className="panel">{state.sessions.filter(s => s.courseId === id).map(s => <SessionRow key={s.id} session={s}/>)}{!state.sessions.some(s => s.courseId === id) && <Empty title="Nothing on the calendar yet" text="Scheduled sessions for this class will appear here."/>}</div> : <Unavailable/>}</>}
    {tab === 'roster' && teacher && <><SectionHeading title={`${roster.length} curious minds`} action={canAdmin(viewer.role) && <Button variant="secondary" onClick={() => setForm('member')}><Plus size={16}/>Add demo learner</Button>}/><div className="panel">{roster.map(m => <div className="roster-row" key={m.id}><Avatar initials={m.initials}/><div><strong>{m.name}</strong><span>{m.email}</span></div><Badge>Enrolled</Badge></div>)}{!roster.length && <Empty title="A fresh classroom" text="Add fictional learners using the teacher + admin demo role."/>}</div></>}
    {form && <ActionForm kind={form} courseId={id} close={() => setForm(null)}/>}</>;
}

export function Sessions({ id }: { id?: string }) {
  const { state, viewer } = useDemo(); const { sessions, teacher } = useScope(); const [form, setForm] = useState(false); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  if (!available(state, viewer, 'live')) return <Unavailable/>;
  const session = id ? sessions.find(s => s.id === id) : undefined;
  if (id && !session) return <Unavailable title="This session isn’t available" text="It may belong to another classroom or organization."/>;
  async function join() { setBusy(true); try { await demoMedia.joinSession(id!); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  if (session) { const course = state.courses.find(c => c.id === session.courseId)!; return <><a className="back-link" href="#/sessions">← Class schedule</a><PageHeading eyebrow="LEARN TOGETHER" title={session.title} description={`${course.subject} · ${course.grade} · ${course.batch}`}/><div className="live-room"><div className="live-room-art"><Video size={48}/><h2>A classroom, wherever you are.</h2><p>Your live session will open here when a provider is connected.</p><Badge tone="light">DEMO · PROVIDER NOT CONNECTED</Badge></div><div className="live-room-details"><h3>Before we begin</h3><div className="detail-row"><CalendarDays size={18}/><span>{dateLabel(session.date)}</span></div><div className="detail-row"><Clock3 size={18}/><span>{timeLabel(session.time)} · {session.duration} minutes</span></div><div className="detail-row"><Users size={18}/><span>{course.studentIds.length} enrolled learners</span></div><p className="muted">Times follow your browser’s local time zone. No camera or microphone access is requested in this demo.</p><Button onClick={join} disabled={busy}><Video size={17}/>{busy ? 'Checking…' : teacher ? 'Check host availability' : 'Check join availability'}</Button>{message && <div className="inline-error" role="status">{message}</div>}<a className="text-link" href={`#/courses/${course.id}`}>Visit course <ArrowUpRight size={15}/></a></div></div></>; }
  return <><PageHeading eyebrow="MAKE TIME FOR DISCOVERY" title="Class schedule" description="A little structure. A lot to look forward to." action={teacher && <Button onClick={() => setForm(true)}><Plus size={17}/>Schedule a class</Button>}/><Notice>Sample schedules only. Live rooms and calendar notifications are not connected.</Notice><div className="schedule-list">{sessions.map(s => <div className="schedule-card" key={s.id}><div className="date-block"><strong>{new Date(`${s.date}T12:00`).getDate()}</strong><span>{new Date(`${s.date}T12:00`).toLocaleDateString('en-IN',{month:'short'})}</span></div><div><span className="eyebrow">{timeLabel(s.time)} · {s.duration} MIN</span><h3>{s.title}</h3><p>{state.courses.find(c => c.id === s.courseId)?.subject} · Sample live session</p></div><a className="button secondary" href={`#/sessions/${s.id}`}>View session <ArrowUpRight size={16}/></a></div>)}</div>{!sessions.length && <Empty title="Your calendar has room to grow" text="Schedule a demo class to get started."/>}{form && <ActionForm kind="session" close={() => setForm(false)}/>}</>;
}

export function Recordings({ id }: { id?: string }) {
  const { state, viewer, act } = useDemo(); const { lessons, teacher } = useScope(); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('all'); const [form, setForm] = useState(false); const [report, setReport] = useState(false); const [reviewed, setReviewed] = useState(false); const [message, setMessage] = useState('');
  if (!available(state, viewer, 'recordings')) return <Unavailable/>;
  const lesson = id ? lessons.find(l => l.id === id) : undefined;
  if (id && !lesson) return <Unavailable title="This lesson isn’t available" text="Only published lessons in your enrolled courses are available to students."/>;
  async function play() { try { await demoMedia.getPlayback(id!); } catch(error) { setMessage((error as Error).message); } }
  if (lesson) { const course = state.courses.find(c => c.id === lesson.courseId)!; return <><a className="back-link" href="#/recordings">← Lesson library</a><PageHeading eyebrow={`${course.subject.toUpperCase()} / ${course.grade.toUpperCase()}`} title={lesson.title} description={`${lesson.duration} minutes · ${lesson.age} · ${course.batch}`}/><div className="lesson-layout"><section><div className={`video-placeholder ${course.color}`}><CourseArt color={course.color} large/><button className="play-button" aria-label="Check recording playback" onClick={play}><Play size={28} fill="currentColor"/></button><div className="video-caption"><span>Recording preview</span><Badge tone="light">No video connected</Badge></div></div>{message && <div className="inline-error" role="status">{message}</div>}<div className="lesson-description"><SectionHeading title="A closer look"/><p>{course.description}</p><Notice>This demo has lesson metadata, not playable media. No video has been uploaded. Completion and review actions below are simulations.</Notice></div></section><aside className="panel lesson-sidebar"><Badge tone={lesson.status === 'published' ? 'sage' : 'peach'}>{lesson.status === 'review' ? 'In review' : lesson.status}</Badge><h3>{teacher ? 'A thoughtful review matters.' : 'Make this lesson your own.'}</h3><p>{teacher ? 'Check curriculum relevance, intended age and subject before making content available to learners.' : 'Take your time. Revisit the ideas, then mark your progress in the local demo.'}</p><div className="detail-row"><ShieldCheck size={17}/>{lesson.age}</div><div className="detail-row"><BookOpen size={17}/>{lesson.subject}</div>{lesson.fileName && <small className="file-name">Local filename: {lesson.fileName}</small>}
      {teacher ? <>{lesson.status === 'draft' && <Button onClick={() => act({type:'lesson-status',id:lesson.id,status:'review',reviewed:false},'Demo draft moved to review. No media was processed.')}><ArrowRight size={16}/>Send to demo review</Button>}{lesson.status === 'review' && <><label className="checkbox-row review-check"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)}/>Simulate teacher approval of this lesson’s age, subject and curriculum suitability.</label><Button disabled={!reviewed} onClick={() => act({type:'lesson-status',id:lesson.id,status:'published',reviewed},'Demo lesson published locally. Real content review remains required.')}><Check size={16}/>Publish demo lesson</Button></>}{lesson.status === 'published' && <><CheckLabel>Visible in the student demo</CheckLabel><Button variant="secondary" onClick={() => {setReviewed(false); act({type:'lesson-status',id:lesson.id,status:'draft',reviewed:false},'Lesson withdrawn in the local demo.');}}>Withdraw to draft</Button></>}</> : <><Button onClick={() => act({type:'complete',id:lesson.id})}><CheckCircle2 size={17}/>{lesson.completeBy.includes(viewer.userId) ? 'Undo demo completion' : 'Mark complete in demo'}</Button><Button variant="ghost" onClick={() => setReport(true)}>Report content</Button></>}
    </aside></div>{report && <ActionForm kind="report" lessonId={lesson.id} close={() => setReport(false)}/>}</>; }
  const filtered = lessons.filter(l => `${l.title} ${l.subject} ${l.age}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'all' || l.status === filter));
  return <><PageHeading eyebrow="IDEAS WORTH COMING BACK TO" title="Lesson library" description={teacher ? 'Create, review and share something worth learning.' : 'Teacher-approved lessons. Your own pace.'} action={teacher && <Button onClick={() => setForm(true)}><Upload size={17}/>Add a recording</Button>}/><div className="list-toolbar"><label className="search-field"><Search size={17}/><input aria-label="Search approved library" placeholder="Search lessons, subjects or ages…" value={search} onChange={e => setSearch(e.target.value)}/></label>{teacher ? <select aria-label="Filter lesson status" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All stages</option><option value="draft">Drafts</option><option value="review">In review</option><option value="published">Published</option></select> : <CheckLabel>Curated educational library</CheckLabel>}</div><div className="recording-grid">{filtered.map(l => { const course=state.courses.find(c=>c.id===l.courseId)!; return <a className="recording-card" href={`#/recordings/${l.id}`} key={l.id}><div className="recording-art"><CourseArt color={course.color}/><span className="mini-play"><Play size={17}/></span><span className="duration">{l.duration} min</span></div><div className="course-card-body"><div className="course-meta"><span>{l.subject}</span><Badge tone={l.status === 'published' ? 'sage' : 'peach'}>{l.status === 'review' ? 'In review' : l.status}</Badge></div><h3>{l.title}</h3><p>{course.grade} · {l.age}</p></div></a>; })}</div>{!filtered.length && <Empty title="No lessons found" text="Try a different search or stage. Only this organization’s available educational catalog is searched."/>}{form && <ActionForm kind="recording" close={() => setForm(false)}/>}</>;
}

export function Assessments() {
  const { state, viewer, act } = useDemo(); const { courses, teacher } = useScope(); const [selected, setSelected] = useState<string | null>(null); const [reviewId, setReviewId] = useState<string | null>(null);
  if (!available(state, viewer, 'assessments')) return <Unavailable/>;
  const assignments = state.assignments.filter(a => a.orgId === viewer.orgId && courses.some(c => c.id === a.courseId));
  const assignment = assignments.find(a => a.id === selected);
  const own = state.submissions.find(s => s.assignmentId === selected && s.studentId === viewer.userId);
  const review = state.submissions.find(s => s.id === reviewId && s.orgId === viewer.orgId && assignments.some(a => a.id === s.assignmentId));
  const reviewAssignment = assignments.find(a => a.id === review?.assignmentId);
  return <><PageHeading eyebrow="A CHANCE TO GROW" title={teacher ? 'Assessment studio' : 'My work & results'} description={teacher ? 'Notice the effort. Help the next idea take shape.' : 'Show what you know, and discover what comes next.'}/><div className="assessment-list">{assignments.map(a => {
    const course = courses.find(c => c.id === a.courseId)!; const sub = state.submissions.find(s => s.assignmentId === a.id && s.studentId === viewer.userId);
    const subs = state.submissions.filter(s => s.assignmentId === a.id && s.orgId === viewer.orgId);
    return <section className="assessment-card" key={a.id}><div className="assessment-heading"><span className={`session-icon ${course.color}`}><ClipboardCheck size={22}/></span><div><div className="eyebrow">{course.subject} · {course.grade}</div><h3>{a.title}</h3><p>Due {dateLabel(a.due)} · {a.points} points</p></div><Badge tone={teacher || sub?.published ? 'sage' : 'peach'}>{teacher ? `${subs.filter(s=>!s.published).length} to review` : sub?.published ? `${sub.score}/${a.points} points` : sub ? 'Submitted' : 'To do'}</Badge></div><p className="assessment-prompt">{a.prompt}</p>{teacher ? <div className="submission-list">{subs.map(s => <div className="submission-row" key={s.id}><Avatar initials={state.members.find(m=>m.id===s.studentId)?.initials || 'L'} small/><div><strong>{state.members.find(m=>m.id===s.studentId)?.name}</strong><span>{s.published ? `Feedback published · ${s.score}/${a.points}` : 'Ready for your feedback'}</span></div><Button variant="secondary" onClick={()=>setReviewId(s.id)}>{s.published ? 'Edit feedback' : 'Review work'}<ArrowUpRight size={15}/></Button></div>)}{!subs.length && <p className="muted">No submissions yet. Try the student demo to submit an answer.</p>}</div> : <div className="assessment-footer">{sub?.published && <p className="feedback"><CheckCircle2 size={17}/>{sub.feedback}</p>}<Button variant="secondary" onClick={()=>setSelected(a.id)}>{sub ? 'View / revise demo work' : 'Open assessment'}<ArrowUpRight size={16}/></Button></div>}</section>;
  })}</div>{!assignments.length && <Empty title="Nothing due. Room to explore." text="Assessments will appear when your teacher shares one."/>}
  {assignment && <Modal title={assignment.title} description="Your answer is saved to this browser demo only." close={()=>setSelected(null)}><form className="form" onSubmit={e=>{e.preventDefault();const answer=String(new FormData(e.currentTarget).get('answer')||'');if(act({type:'submit',id:assignment.id,answer},'Demo answer submitted locally. No work was sent to a teacher.'))setSelected(null);}}><p>{assignment.prompt}</p><Field label="Your answer"><textarea name="answer" required rows={6} maxLength={4000} defaultValue={own?.answer} autoFocus/></Field>{own?.published && <Notice>Revising a demo submission clears its published grade until reviewed again.</Notice>}<div className="form-actions"><Button type="button" variant="secondary" onClick={()=>setSelected(null)}>Cancel</Button><Button type="submit">Submit in demo <ArrowRight size={16}/></Button></div></form></Modal>}
  {review && reviewAssignment && teacher && <Modal title="A little feedback goes a long way" description={`${state.members.find(m=>m.id===review.studentId)?.name} · ${reviewAssignment.title}`} close={()=>setReviewId(null)}><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(act({type:'grade',id:review.id,score:Number(f.get('score')),feedback:String(f.get('feedback'))},'Feedback published to the local student demo.'))setReviewId(null);}}><div className="answer-box"><span className="eyebrow">LEARNER’S ANSWER</span><p>{review.answer}</p></div><Field label={`Score (out of ${reviewAssignment.points})`}><input name="score" type="number" required min="0" max={reviewAssignment.points} defaultValue={review.score ?? ''}/></Field><Field label="Helpful feedback"><textarea name="feedback" required rows={3} maxLength={1500} defaultValue={review.feedback || ''} placeholder="What worked well? What could they explore next?"/></Field><Button type="submit"><Check size={16}/>Publish demo feedback</Button></form></Modal>}
  </>;
}

export function Attendance() {
  const { state, viewer, act } = useDemo(); const { sessions, courses, teacher } = useScope(); const [sessionId, setSessionId] = useState(sessions[0]?.id || '');
  if (!teacher) return <Unavailable title="A teaching space" text="Attendance editing is available to teachers in this demo."/>;
  if (!available(state, viewer, 'attendance')) return <Unavailable/>;
  const session=sessions.find(s=>s.id===sessionId);const course=courses.find(c=>c.id===session?.courseId);
  return <><PageHeading eyebrow="EVERY LEARNER COUNTS" title="Attendance" description="A simple register. More time for the people in it."/><div className="list-toolbar"><Field label="Class session"><select aria-label="Class session" value={sessionId} onChange={e=>setSessionId(e.target.value)}>{sessions.map(s=><option key={s.id} value={s.id}>{dateLabel(s.date)} · {s.title}</option>)}</select></Field><span className="muted">{course?.batch}</span></div>{session && course ? <AttendanceRegister key={`${sessionId}-${viewer.orgId}`} sessionId={sessionId} studentIds={course.studentIds} onSave={values=>act({type:'attendance',sessionId,values},'Attendance saved in this browser demo only.')}/> : <Empty title="No session selected" text="Schedule a class to start its attendance register."/>}</>;
}
function AttendanceRegister({sessionId,studentIds,onSave}:{sessionId:string;studentIds:string[];onSave:(values:Record<string,AttendanceStatus>)=>boolean}) {
  const {state}=useDemo();const [values,setValues]=useState<Record<string,AttendanceStatus>>(state.attendance[sessionId]||{});const [dirty,setDirty]=useState(false);
  const members=state.members.filter(m=>studentIds.includes(m.id));const present=Object.values(values).filter(v=>v==='present').length;
  return <><div className="panel"><SectionHeading title={`${members.length} learners`} action={<Button variant="secondary" onClick={()=>{setValues(Object.fromEntries(members.map(m=>[m.id,'present'])));setDirty(true);}}><Check size={16}/>Mark all present</Button>}/><div className="table-wrap"><table><thead><tr><th>Learner</th><th>Attendance status</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><div className="table-person"><Avatar initials={m.initials} small/><span>{m.name}</span></div></td><td><div className="attendance-options" role="group" aria-label={`Attendance for ${m.name}`}>{(['present','late','absent'] as const).map(status=><button key={status} className={values[m.id]===status?`selected ${status}`:''} aria-pressed={values[m.id]===status} onClick={()=>{setValues({...values,[m.id]:status});setDirty(true);}}>{status}</button>)}</div></td></tr>)}</tbody></table></div>{!members.length&&<Empty title="No learners enrolled" text="An admin-assigned teacher can add fictional learners to this course."/>}</div><div className="save-bar"><span>{present} present · {members.length-Object.keys(values).length} unmarked {dirty?'· Unsaved demo changes':''}</span><Button disabled={!dirty} onClick={()=>{if(onSave(values))setDirty(false);}}>Save demo attendance <Check size={16}/></Button></div></>;
}

export function Settings() {
  const {state,viewer,act}=useDemo();const [form,setForm]=useState(false);const org=state.orgs.find(o=>o.id===viewer.orgId)!;
  if(!canAdmin(viewer.role))return <Unavailable title="Organization settings are restricted" text="Only explicitly assigned teacher-admins have this demo view. Ordinary teachers do not receive administrator permissions."/>;
  return <><PageHeading eyebrow="A PLACE TO BELONG" title="Organization settings" description="A few thoughtful settings for your shared learning space."/><div className="settings-grid"><section className="panel"><h2>Organization profile</h2><p className="muted">One organization, wherever learning happens.</p><form className="form" onSubmit={e=>{e.preventDefault();act({type:'rename',name:String(new FormData(e.currentTarget).get('name'))});}}><Field label="Organization name"><input name="name" required defaultValue={org.name} maxLength={80}/></Field><Notice>You have an explicit teacher-admin assignment in this demo. Feature changes remain in the platform preview.</Notice><Button type="submit">Save demo settings</Button></form></section><section className="panel"><h2>Enabled features</h2><p className="muted">Feature access and people’s permissions are separate.</p>{(Object.entries(featureLabels) as [Feature,string][]).map(([key,label])=><div className="setting-row" key={key}><span>{label}</span><Badge tone={org.features[key]?'sage':'neutral'}>{org.features[key]?'Enabled':'Not enabled'}</Badge></div>)}</section></div><SectionHeading title="People in your organization" action={<Button variant="secondary" onClick={()=>setForm(true)}><Plus size={16}/>Add demo learner</Button>}/><div className="panel">{state.members.filter(m=>m.orgId===viewer.orgId).map(m=><div className="roster-row" key={m.id}><Avatar initials={m.initials}/><div><strong>{m.name}</strong><span>{m.email}</span></div><Badge tone="neutral">{m.role}</Badge></div>)}</div><section className="panel report-panel"><SectionHeading title="Demo content reports"/>{state.reports.filter(r=>r.orgId===viewer.orgId).length ? state.reports.filter(r=>r.orgId===viewer.orgId).map((r,i)=><div className="report-row" key={i}><strong>{state.lessons.find(l=>l.id===r.lessonId)?.title}</strong><p>{r.reason}</p><a className="text-link" href={`#/recordings/${r.lessonId}`}>Review lesson <ArrowUpRight size={14}/></a></div>) : <p className="muted">No reports in this browser demo. Student reports appear here for review.</p>}</section>{form&&<ActionForm kind="member" close={()=>setForm(false)}/>}</>;
}

export function Organizations() {
  const {state,viewer,act}=useDemo();const [form,setForm]=useState(false);const [selected,setSelected]=useState(state.orgs[0]?.id||'genix');
  if(viewer.role!=='super-admin')return <Unavailable title="Platform access is restricted" text="Use the clearly labeled platform demo persona to preview these controls."/>;
  const org=state.orgs.find(o=>o.id===selected)||state.orgs[0];
  return <><PageHeading eyebrow="PLATFORM WORKSPACE" title="Room for every organization" description="Independent learning spaces. Thoughtful controls." action={<Button onClick={()=>setForm(true)}><Plus size={17}/>Create organization</Button>}/><Notice>Platform demo only. All usage below is fictional local inventory, not measured provider billing or subscription data.</Notice><div className="platform-grid"><div className="org-list">{state.orgs.map(o=><button key={o.id} className={`org-card ${org.id===o.id?'active':''}`} onClick={()=>setSelected(o.id)}><span className="org-symbol">{o.name.charAt(0)}</span><div><strong>{o.name}</strong><small>{Object.values(o.features).filter(Boolean).length} enabled features</small></div><span className={`status-dot ${o.active?'':'off'}`}/></button>)}</div><section className="panel org-detail"><div className="section-heading"><h2>{org.name}</h2><Badge tone={org.active?'sage':'peach'}>{org.active?'Active':'Suspended'}</Badge></div><div className="mini-stats"><div><strong>{state.courses.filter(c=>c.orgId===org.id).length}</strong><span>Demo courses</span></div><div><strong>{state.members.filter(m=>m.orgId===org.id).length}</strong><span>Demo people</span></div><div><strong>{state.lessons.filter(l=>l.orgId===org.id).length}</strong><span>Lesson records</span></div></div><h3>Organization features</h3><p className="muted">Switches change this organization’s local demo only.</p>{(Object.entries(featureLabels) as [Feature,string][]).map(([key,label])=><div className="setting-row" key={key}><span>{label}</span><button className={`toggle ${org.features[key]?'on':''}`} role="switch" aria-checked={org.features[key]} aria-label={`${label} for ${org.name}`} onClick={()=>act({type:'feature',orgId:org.id,feature:key},`${label} changed for ${org.name} in the demo only.`)}><span/></button></div>)}<p className="fine-print">Disabling a feature hides its demo views; existing local records are preserved. No subscription or billing change occurs.</p><div className="org-status-action"><Button variant={org.active?'secondary':'primary'} onClick={()=>act({type:'org-status',orgId:org.id},`${org.name} ${org.active?'suspended':'restored'} in the local demo.`)}>{org.active?'Suspend demo organization':'Restore demo organization'}</Button></div></section></div>{form&&<ActionForm kind="organization" close={()=>setForm(false)}/>}</>;
}

export function DemoAccess({ enter }: { enter: () => void }) {
  return <div className="access-page"><div className="access-emblem"><GraduationCap size={32}/></div><span className="eyebrow">GREAT GENIX</span><h1>A little curiosity.<br/>A world of possibility.</h1><p>Explore the teacher and student experience with fictional data. No account or password needed.</p><Button onClick={enter}>Enter the local demo <ArrowRight size={17}/></Button><Notice>Real sign-in, recovery and invitations will use Supabase Auth. They are not connected in this prototype.</Notice></div>;
}
